#!/usr/bin/env node

const { execSync, spawnSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const RESET = "\x1b[0m";
const BOLD = "\x1b[1m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const RED = "\x1b[31m";
const CYAN = "\x1b[36m";

function log(msg) { console.log(msg); }
function step(msg) { console.log(`\n${BOLD}${CYAN}▶ ${msg}${RESET}`); }
function success(msg) { console.log(`${GREEN}✔ ${msg}${RESET}`); }
function warn(msg) { console.log(`${YELLOW}⚠ ${msg}${RESET}`); }
function error(msg) { console.error(`${RED}✖ ${msg}${RESET}`); }

function run(cmd) {
  try {
    execSync(cmd, { encoding: "utf8", stdio: "inherit" });
    return true;
  } catch {
    return false;
  }
}

function runCapture(cmd) {
  const result = spawnSync(cmd, { shell: true, encoding: "utf8", maxBuffer: 10 * 1024 * 1024 });
  return { stdout: result.stdout ?? "", stderr: result.stderr ?? "", status: result.status };
}

// ─── Step 1: Install dependencies ────────────────────────────────────────────

step("Installing npm dependencies…");
if (!run("npm install")) {
  error("npm install failed.");
  process.exit(1);
}
success("Dependencies installed.");

// ─── Step 2: Start Supabase ───────────────────────────────────────────────────

step("Starting local Supabase instance…");

const statusResult = runCapture("npx supabase status");
const alreadyRunning = statusResult.status === 0 && statusResult.stdout.includes("API URL");

let supabaseOutput = "";

if (alreadyRunning) {
  warn("Supabase is already running — using existing instance.");
  supabaseOutput = statusResult.stdout;
} else {
  log("  Starting Supabase (this may take a minute on first run)…");
  const startResult = runCapture("npx supabase start");
  if (startResult.status !== 0) {
    error("Failed to start Supabase. Is Docker running?");
    log(startResult.stderr);
    process.exit(1);
  }
  supabaseOutput = startResult.stdout + startResult.stderr;
  success("Supabase started.");
}

// ─── Step 3: Extract credentials ─────────────────────────────────────────────

step("Extracting Supabase credentials…");

let urlMatch = supabaseOutput.match(/API URL:\s*(https?:\/\/\S+)/);
let keyMatch = supabaseOutput.match(/anon key:\s*(\S+)/);

if (!urlMatch || !keyMatch) {
  const fresh = runCapture("npx supabase status");
  urlMatch = fresh.stdout.match(/API URL:\s*(https?:\/\/\S+)/);
  keyMatch = fresh.stdout.match(/anon key:\s*(\S+)/);

  if (!urlMatch || !keyMatch) {
    error("Could not parse Supabase credentials. Set them manually in .env.local");
    process.exit(1);
  }
}

const supabaseUrl = urlMatch[1].trim();
const supabaseAnonKey = keyMatch[1].trim();

success(`Supabase URL: ${supabaseUrl}`);
success(`Anon key:     ${supabaseAnonKey.slice(0, 20)}…`);

// ─── Step 4: Write .env.local ─────────────────────────────────────────────────

step("Writing .env.local…");

const envPath = path.join(__dirname, ".env.local");
const envContent = `# Auto-generated by setup.js on ${new Date().toISOString()}
# Do not commit this file — it is listed in .gitignore

NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnonKey}
`;

if (fs.existsSync(envPath)) {
  warn(".env.local already exists — overwriting with fresh credentials.");
}

fs.writeFileSync(envPath, envContent, "utf8");
success(".env.local written.");

// ─── Step 5: Run migrations ───────────────────────────────────────────────────

step("Running database migrations…");

const resetResult = runCapture("npx supabase db reset");
if (resetResult.status !== 0) {
  error("Database migration failed:");
  log(resetResult.stderr);
  process.exit(1);
}
success("Migrations applied.");

// ─── Done ─────────────────────────────────────────────────────────────────────

log(`
${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Setup complete! 🚀
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}

Next steps:
  ${BOLD}npm run dev${RESET}        Start the development server
  ${BOLD}npm test${RESET}           Run the test suite
  ${BOLD}open http://localhost:3000${RESET}

Supabase Studio:   ${CYAN}http://127.0.0.1:54323${RESET}
Inbucket (email):  ${CYAN}http://127.0.0.1:54324${RESET}
`);